//*****************************************************************************//
// INTERFACE.H
//		本文件对底层电磁铁驱动板驱动板按顺序进行定义
//		便于增强程序的可读性
//*****************************************************************************//

#ifndef   __INTERFACE_H__
#define   __INTERFACE_H__

///////////////////////////////////////////////////////////////////////////////
// 对0至47个电磁铁驱动板进行定义
///////////////////////////////////////////////////////////////////////////////
#define DCT_Driver_0		0	         	// 0号电磁铁驱动板
#define DCT_Driver_1		1	         	// 1号电磁铁驱动板
#define DCT_Driver_2		2	         	// 2号电磁铁驱动板
#define DCT_Driver_3		3	         	// 3号电磁铁驱动板
#define DCT_Driver_4		4	         	// 4号电磁铁驱动板
#define DCT_Driver_5		5	         	// 5号电磁铁驱动板
#define DCT_Driver_6		6	         	// 6号电磁铁驱动板
#define DCT_Driver_7		7	         	// 7号电磁铁驱动板
#define DCT_Driver_8		8	         	// 8号电磁铁驱动板
#define DCT_Driver_9		9	         	// 9号电磁铁驱动板
#define DCT_Driver_10		10	         	// 10号电磁铁驱动板
#define DCT_Driver_11		11	         	// 11号电磁铁驱动板
#define DCT_Driver_12		12	         	// 12号电磁铁驱动板
#define DCT_Driver_13		13	         	// 13号电磁铁驱动板
#define DCT_Driver_14		14	         	// 14号电磁铁驱动板
#define DCT_Driver_15		15	         	// 15号电磁铁驱动板
#define DCT_Driver_16		16	         	// 16号电磁铁驱动板
#define DCT_Driver_17		17	         	// 17号电磁铁驱动板
#define DCT_Driver_18		18	         	// 18号电磁铁驱动板
#define DCT_Driver_19		19	         	// 19号电磁铁驱动板
#define DCT_Driver_20		20	         	// 20号电磁铁驱动板
#define DCT_Driver_21		21	         	// 21号电磁铁驱动板
#define DCT_Driver_22		22	         	// 22号电磁铁驱动板
#define DCT_Driver_23		23	         	// 23号电磁铁驱动板
#define DCT_Driver_24		24	         	// 24号电磁铁驱动板
#define DCT_Driver_25		25	         	// 25号电磁铁驱动板
#define DCT_Driver_26		26	         	// 26号电磁铁驱动板
#define DCT_Driver_27		27	         	// 27号电磁铁驱动板
#define DCT_Driver_28		28	         	// 28号电磁铁驱动板
#define DCT_Driver_29		29	         	// 29号电磁铁驱动板
#define DCT_Driver_30		30	         	// 30号电磁铁驱动板
#define DCT_Driver_31		31	         	// 31号电磁铁驱动板
#define DCT_Driver_32		32	         	// 32号电磁铁驱动板
#define DCT_Driver_33		33	         	// 33号电磁铁驱动板
#define DCT_Driver_34		34	         	// 34号电磁铁驱动板
#define DCT_Driver_35		35	         	// 35号电磁铁驱动板
#define DCT_Driver_36		36	         	// 36号电磁铁驱动板
#define DCT_Driver_37		37	         	// 37号电磁铁驱动板
#define DCT_Driver_38		38	         	// 38号电磁铁驱动板
#define DCT_Driver_39		39	         	// 39号电磁铁驱动板
#define DCT_Driver_40		40	         	// 40号电磁铁驱动板
#define DCT_Driver_41		41	         	// 33号电磁铁驱动板
#define DCT_Driver_42		42	         	// 34号电磁铁驱动板
#define DCT_Driver_43		43	         	// 35号电磁铁驱动板
#define DCT_Driver_44		44	         	// 36号电磁铁驱动板
#define DCT_Driver_45		45	         	// 37号电磁铁驱动板
#define DCT_Driver_46		46	         	// 38号电磁铁驱动板
#define DCT_Driver_47		47	         	// 39号电磁铁驱动板


#endif